export const SCHOOL = {
  name: "Scribbles International PreSchool",
  shortName: "Scribbles",
  tagline: "Learn • Explore • Grow",
  location: "Venkat Reddy Colony, 28 K.P, 100 Feet Road, Madhavi Nagar, Kalluru, Kurnool, Andhra Pradesh – 518002",
  phone: "+91 83339 69774",
  email: "info@scribblespreschool.com",
  googleRating: 4.7,
  googleReviews: 14,
  type: "Montessori-based Preschool",
  identity: "Women-owned institution",
  whatsapp: "918333969774",
  mapEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3848.0!2d78.0!3d15.8!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMTXCsDQ4JzAwLjAiTiA3OMKwMDAnMDAuMCJF!5e0!3m2!1sen!2sin!4v1",
  social: {
    facebook: "https://facebook.com/scribblespreschool",
    instagram: "https://instagram.com/scribblespreschool",
    youtube: "https://youtube.com/@scribblespreschool",
  },
} as const;

export const NAV_LINKS = [
  { label: "Home", href: "/" },
  { label: "About Us", href: "/about" },
  { label: "Programs", href: "/programs" },
  { label: "Facilities", href: "/facilities" },
  { label: "Gallery", href: "/gallery" },
  { label: "Admissions", href: "/admissions" },
  { label: "Testimonials", href: "/testimonials" },
  { label: "Contact", href: "/contact" },
  { label: "FAQ", href: "/faq" },
] as const;

export const PROGRAMS = [
  {
    id: "play-group",
    title: "Play Group",
    age: "1.5 - 2.5 Years",
    duration: "2 Hours/Day",
    ratio: "1:8",
    description: "A gentle introduction to school life through play-based learning in a nurturing environment.",
    outcomes: [
      "Social interaction skills",
      "Basic motor development",
      "Sensory exploration",
      "Language exposure",
      "Emotional security",
    ],
    activities: [
      "Free play & exploration",
      "Story telling sessions",
      "Art & craft",
      "Music & movement",
      "Sensory play",
    ],
    color: "pastel-yellow",
    icon: "🧸",
  },
  {
    id: "nursery",
    title: "Nursery",
    age: "2.5 - 3.5 Years",
    duration: "3 Hours/Day",
    ratio: "1:10",
    description: "Building foundational skills through structured play and guided discovery.",
    outcomes: [
      "Language development",
      "Pre-math concepts",
      "Fine motor skills",
      "Social etiquette",
      "Independence building",
    ],
    activities: [
      "Circle time",
      "Phonics introduction",
      "Numbers & counting",
      "Show & tell",
      "Outdoor play",
    ],
    color: "pastel-blue",
    icon: "📚",
  },
  {
    id: "pre-kg",
    title: "Pre-KG",
    age: "3.5 - 4.5 Years",
    duration: "3.5 Hours/Day",
    ratio: "1:12",
    description: "Preparing children for formal schooling with enhanced cognitive and social development.",
    outcomes: [
      "Letter & sound recognition",
      "Number sense (1-50)",
      "Writing readiness",
      "Problem-solving skills",
      "Classroom routines",
    ],
    activities: [
      "Montessori activities",
      "Language & phonics",
      "Math manipulatives",
      "Creative arts",
      "Group projects",
    ],
    color: "pastel-mint",
    icon: "✏️",
  },
  {
    id: "lkg",
    title: "LKG",
    age: "4.5 - 5.5 Years",
    duration: "4 Hours/Day",
    ratio: "1:15",
    description: "Structured learning with focus on literacy, numeracy, and holistic development.",
    outcomes: [
      "Reading simple words",
      "Writing sentences",
      "Basic addition/subtraction",
      "Environmental awareness",
      "Confidence & expression",
    ],
    activities: [
      "Reading & writing",
      "Math exercises",
      "EVS projects",
      "Rhymes & stories",
      "Yoga & mindfulness",
    ],
    color: "pastel-pink",
    icon: "🎨",
  },
  {
    id: "ukg",
    title: "UKG",
    age: "5.5 - 6.5 Years",
    duration: "4.5 Hours/Day",
    ratio: "1:15",
    description: "Comprehensive school readiness program ensuring smooth transition to formal education.",
    outcomes: [
      "Fluent reading",
      "Creative writing",
      "Math operations",
      "Scientific thinking",
      "School readiness",
    ],
    activities: [
      "Advanced literacy",
      "Math explorations",
      "Science experiments",
      "Public speaking",
      "Field trips",
    ],
    color: "pastel-purple",
    icon: "🌟",
  },
] as const;

export const FACILITIES = [
  { title: "Smart Classrooms", description: "Interactive digital boards and modern teaching aids for engaging learning experiences.", icon: "💻", color: "pastel-blue" },
  { title: "Play Areas", description: "Safe, well-equipped indoor and outdoor play zones designed for physical development.", icon: "🎠", color: "pastel-yellow" },
  { title: "Montessori Labs", description: "Specially designed Montessori materials and environments for self-directed learning.", icon: "🔬", color: "pastel-mint" },
  { title: "Activity Rooms", description: "Dedicated spaces for art, music, dance, and creative expression.", icon: "🎭", color: "pastel-pink" },
  { title: "Safe Campus", description: "Child-safe infrastructure with rounded corners, non-slip floors, and secure entry points.", icon: "🛡️", color: "pastel-blue" },
  { title: "CCTV Security", description: "24/7 CCTV surveillance with live monitoring for complete peace of mind.", icon: "📹", color: "pastel-purple" },
  { title: "Hygienic Environment", description: "Regular sanitization, purified water, and strict cleanliness protocols throughout.", icon: "✨", color: "pastel-mint" },
  { title: "Library Corner", description: "Age-appropriate books and reading materials to foster early literacy skills.", icon: "📖", color: "pastel-yellow" },
  { title: "Nutritious Meals", description: "Healthy, hygienic meals and snacks planned by nutrition experts.", icon: "🥗", color: "pastel-pink" },
  { title: "Transport Facility", description: "Safe and reliable door-step pick-up and drop-off service with trained attendants.", icon: "🚌", color: "pastel-blue" },
] as const;

export const TESTIMONIALS = [
  { name: "Priya Sharma", child: "LKG Student", text: "Absolutely beautiful classrooms and play areas for kids. My daughter loves going to school every day!", rating: 5 },
  { name: "Rajesh Kumar", child: "UKG Student", text: "Teachers, staff, management; everything is great about this school. Highly recommended!", rating: 5 },
  { name: "Anita Reddy", child: "Nursery Student", text: "Safe, friendly and nurturing environment. My son has improved so much in his social skills.", rating: 5 },
  { name: "Sunil Verma", child: "Pre-KG Student", text: "The Montessori approach here is fantastic. My child's cognitive development has been remarkable.", rating: 5 },
  { name: "Kavitha Nair", child: "Play Group Student", text: "Wonderful teachers who truly care. The transition from home to school was so smooth.", rating: 4 },
  { name: "Arun Patel", child: "LKG Student", text: "Excellent infrastructure and well-trained staff. The smart classrooms are a big plus.", rating: 5 },
  { name: "Deepa Iyer", child: "UKG Student", text: "My daughter has become so confident and expressive. Thank you Scribbles for the amazing foundation.", rating: 5 },
  { name: "Venkat Rao", child: "Nursery Student", text: "Best preschool in Kurnool! The CCTV access and regular updates give us complete peace of mind.", rating: 5 },
] as const;

export const GALLERY_IMAGES = [
  { src: "/gallery/classroom-1.jpg", alt: "Bright colorful classroom with learning stations", category: "Classrooms" },
  { src: "/gallery/play-area-1.jpg", alt: "Children playing in indoor play area", category: "Play Areas" },
  { src: "/gallery/montessori-1.jpg", alt: "Montessori lab with learning materials", category: "Montessori Lab" },
  { src: "/gallery/activity-1.jpg", alt: "Art and craft activity session", category: "Activities" },
  { src: "/gallery/event-1.jpg", alt: "Annual day celebration", category: "Events" },
  { src: "/gallery/classroom-2.jpg", alt: "Reading corner in classroom", category: "Classrooms" },
  { src: "/gallery/outdoor-1.jpg", alt: "Outdoor play equipment", category: "Play Areas" },
  { src: "/gallery/activity-2.jpg", alt: "Music and dance session", category: "Activities" },
  { src: "/gallery/library-1.jpg", alt: "Library corner with books", category: "Classrooms" },
  { src: "/gallery/event-2.jpg", alt: "Children's day celebration", category: "Events" },
  { src: "/gallery/montessori-2.jpg", alt: "Sensorial activities", category: "Montessori Lab" },
  { src: "/gallery/play-area-2.jpg", alt: "Ball pit and slides", category: "Play Areas" },
] as const;

export const FAQS = [
  { q: "What is the admission age for Play Group?", a: "Children aged 1.5 to 2.5 years are eligible for Play Group admission." },
  { q: "What is the student-teacher ratio?", a: "We maintain a low student-teacher ratio ranging from 1:8 for Play Group to 1:15 for UKG to ensure individual attention." },
  { q: "Is CCTV monitoring available for parents?", a: "Yes, we have 24/7 CCTV surveillance. Parents can request access to monitor their child's activities." },
  { q: "What curriculum does Scribbles follow?", a: "We follow a Montessori-based curriculum combined with modern early childhood education practices." },
  { q: "Are meals provided at school?", a: "Yes, we provide nutritious and hygienic meals and snacks planned by nutrition experts." },
  { q: "Do you offer transportation?", a: "Yes, we provide safe door-step pick-up and drop-off services with trained attendants." },
  { q: "What are the school timings?", a: "School timings vary by program: Play Group (2 hrs), Nursery (3 hrs), Pre-KG (3.5 hrs), LKG (4 hrs), UKG (4.5 hrs)." },
  { q: "How can I schedule a school visit?", a: "You can call us at +91 83339 69774 or fill the enquiry form on our website to schedule a visit." },
] as const;

export const STATS = [
  { value: "4.7", suffix: "★", label: "Google Rating", color: "star" },
  { value: "Montessori", suffix: "", label: "Curriculum", color: "accent" },
  { value: "Safe", suffix: "", label: "Environment", color: "primary" },
  { value: "Experienced", suffix: "", label: "Teachers", color: "warm" },
] as const;
